<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-16T20:12:19 IST" name="Suite" finished-at="2025-01-16T20:12:25 IST" duration-ms="5717">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.LoginError()[pri:0, instance:rahulshettyacademy.tests.ErrorValidationTest@26d9b808]" name="LoginError" class="rahulshettyacademy.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2025-01-16T20:12:19 IST" name="Test" finished-at="2025-01-16T20:12:25 IST" duration-ms="5717">
      <class name="rahulshettyacademy.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.tests.ErrorValidationTest@26d9b808]" started-at="2025-01-16T20:12:19 IST" name="launchApplication" finished-at="2025-01-16T20:12:24 IST" duration-ms="4641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginError()[pri:0, instance:rahulshettyacademy.tests.ErrorValidationTest@26d9b808]" started-at="2025-01-16T20:12:24 IST" name="LoginError" finished-at="2025-01-16T20:12:25 IST" duration-ms="948" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulshettyacademy.tests.ErrorValidationTest@26d9b808]" started-at="2025-01-16T20:12:25 IST" name="tearDown" finished-at="2025-01-16T20:12:25 IST" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahulshettyacademy.tests.ErrorValidationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
